### ISSUE TITLE
헬스장 및 그룹 커뮤니티 페이지 구현

### ISSUE THREAD

**Issue by k906506** [TEAM-Strap/Strap-AOS#8]
## Description
- 로그인 이후 헬스장 선택 및 그룹 커뮤니티 가입 페이지 구현
- 총 5개의 페이지로 구현하며 Firestore에서 그룹 커뮤니티 가입 여부 확인하고 본 페이지로 이동
- 그룹 커뮤니티 가입 완료 후 Firestore 업데이트

## Todo
- [x] 페이지 1 : 가입 설명
- [x] 페이지 2 : 헬스장 선택
- [x] 페이지 3 : 그룹 커뮤니티 선택
- [x] 페이지 4 : 그룹 커뮤니티 상세
- [x] 페이지 5 : 가입 확인
